[littlesnitch]
source = "regex"
url = "https://obdev.at/products/littlesnitch-linux/download.html"
regex = 'littlesnitch-([0-9]+\.[0-9]+\.[0-9]+-[0-9]+)-x86_64\.pkg\.tar\.zst'
from_pattern = '^(.*)-([0-9]+)$'
to_pattern = '\1_\2'
